### ISSUE TITLE
detect-speed did not work

### ISSUE THREAD

**Issue by tshmak** [swesterfeld/audiowmark#10]
Hi, 

I tried a simple sox `tempo` transform, and `--detect-speed` was not able to recover the message. I wonder if it is because of my audio or if there's a bug in the program. Would you be able to provide an example where `detect-speed` works as expected? 

Many thanks for your help! 

Tim

**Comment by swesterfeld** [comment]
I think this is a misunderstanding of what `--detect-speed` does. It doesn't detect/correct time stretching (which I believe is what `sox tempo` does) but replay speed changes (change both: tempo and pitch `sox speed`). An example can be found in the README section on speed detection, the sox command is `sox out.wav out1.wav speed 1.05`.

See
 - https://github.com/swesterfeld/audiowmark#speed
