### ISSUE TITLE
Unable to stream mp3 to stdin of audiowmark?

### ISSUE THREAD

**Issue by uncvrd** [swesterfeld/audiowmark#13]
I have a use case to watermark mp3 files streamed in to `stdin` of `audiowmark`. Since mp3 files do not contain the proper headers required for obtaining metadata necessary for watermarking with a stream, I'd need to use `--format raw` and manually set some options. However since mp3 files do not contain a bit depth (right? [Source here](https://stackoverflow.com/questions/27652123/how-to-know-the-bit-depth-of-a-mp3-file)), I would be unable to set the `--raw-bits` flag.

Given this scenario, do I understand correctly that I'd need to load the mp3 file completely in memory and then simply pass the whole file to `audiowmark` to handle to bypass this streaming input limitation?

Also one thing I've noticed is that when I load the entire mp3 file in to memory (7MB) and then pass it to `audiowmark` the output mp3 file size is almost 5x bigger (~50MB). When doing the same with WAVs the conversion is close to 1:1.

Again, as mentioned in my previous issue, thanks for your excellent work on this library!

**Comment by swesterfeld** [comment]
> [...] do I understand correctly that I'd need to load the mp3 file completely in memory and then simply pass the whole file to `audiowmark` to handle to bypass this streaming input limitation?

This is not really a bug, so I think it makes sense for me to write a mail to the google group of how to do it:

https://groups.google.com/g/audiowmark/c/1PPrvwOHhSo

> Also one thing I've noticed is that when I load the entire mp3 file in to memory (7MB) and then pass it to `audiowmark` the output mp3 file size is almost 5x bigger (~50MB). When doing the same with WAVs the conversion is close to 1:1.

This is because audiowmark always uses uncompressed wav as output format.

**Comment by uncvrd** [comment]
Thank you for the extremely detailed response, exactly what I needed - sorry for posting this as a "bug" I didn't realize a Google Groups existed!
