### ISSUE TITLE
Big audio files cropped

### ISSUE THREAD

**Issue by mnordstr** [swesterfeld/audiowmark#2]
Hi,

I'm evaluating this with the use of bigger audio files, several tens of hours.

When testing a bigger 5Gb wav, the process looks ok but the resulting watermarked file is smaller (around 4G). ffprobe gives:

Original
Duration: 17:17:22.09, bitrate: 705 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 1 channels, s16, 705 kb/s

Watermarked:
Duration: 13:31:35.77, bitrate: 705 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 1 channels, s16, 705 kb/s

The output file size is **4294967338**, which I find to be too close to be a coincidence with what stdint.h defines for size_t:

```c
/* Limit of `size_t' type.  */
# if __WORDSIZE == 64
#  define SIZE_MAX              (18446744073709551615UL)
# else
#  define SIZE_MAX              (4294967295U)
# endif
```

I'm guessing some counter somewhere should not limit it to that, haven't found out where yet.

**Comment by swesterfeld** [comment]
I am not convinced that the watermarking code itself has a problem. If I use raw streams,
```
$ dd if=/dev/zero bs=1M count=10000 | audiowmark add - - f0 --format raw --raw-rate 44100 --raw-channels 1 --raw-bits 16 | wc -c
Input:        -
Raw Input:    44100 Hz, 1 Channels, 16 Bit (signed little-endian)
Output:       -
Raw Output:   44100 Hz, 1 Channels, 16 Bit (signed little-endian)
Message:      f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0
Strength:     10

Time:         unknown
Sample Rate:  44100
Channels:     1
10000+0 records in
10000+0 records out
10485760000 bytes (10 GB, 9.8 GiB) copied, 95.0188 s, 110 MB/s
Data Blocks:  2300
10485760000
```
the last number here is the number of bytes written by the watermarker. This file is a lot larger than 4GB. What I assume is happening is that standard .wav files are by design limited to at most 4GB because the wav header has a 32bit unsigned size field. Then maybe we only need to instruct libsndfile to write a file that can be longer, for instance using SF_FORMAT_RF64 instead of SF_FORMAT_WAV sfoutputstream.cc (didn't test this change).

**Comment by mnordstr** [comment]
After research I came to the same conclusion.

I made a small patch that forces it to RF64 which seems to work:

```patch
--- origawmrk/src/sfoutputstream.cc     2020-12-11 10:08:04.138117445 +0100
+++ awmarksrc/src/sfoutputstream.cc     2020-12-11 09:35:43.067347445 +0100
@@ -51,7 +51,7 @@

    switch (out_format)
      {
-       case OutFormat::WAV:  sfinfo.format = SF_FORMAT_WAV;
+       case OutFormat::WAV:  sfinfo.format = SF_FORMAT_RF64;
                              break;
        case OutFormat::FLAC: sfinfo.format = SF_FORMAT_FLAC;
                              break;
@@ -103,8 +103,8 @@
   for (size_t i = 0; i < samples.size(); i++)
     {
       const double norm      =  0x80000000LL;
-      const double min_value = -0x80000000LL;
-      const double max_value =  0x7FFFFFFF;
+      const double min_value =  0x00000000LL;
+      const double max_value =  0xFFFFFFFF;

       isamples[i] = lrint (bound<double> (min_value, samples[i] * norm, max_value));
     }
diff -u -x '*[^cchh]' origawmrk/src/wmadd.cc awmarksrc/src/wmadd.cc
--- origawmrk/src/wmadd.cc      2020-12-11 10:08:04.138117445 +0100
+++ awmarksrc/src/wmadd.cc      2020-12-11 10:10:57.168068364 +0100
@@ -636,8 +636,8 @@
     }
   else
     {
-      int orig_seconds = in_stream->n_frames() / in_stream->sample_rate();
-      info ("Time:         %d:%02d\n", orig_seconds / 60, orig_seconds % 60);
+      uint orig_seconds = in_stream->n_frames() / in_stream->sample_rate();
+      info ("Time:         %u:%02u\n", orig_seconds / 60, orig_seconds % 60);
     }
   info ("Sample Rate:  %d\n", in_stream->sample_rate());
   info ("Channels:     %d\n", in_stream->n_channels());
```

However, when I try to check the watermark on a file created like this it does not find anything. Small and big files. Audio metadata seems correct and sounds ok. Looking through the wmget.cc file I can't seem to find anything that might fix it. Any ideas what may cause it?

**Comment by swesterfeld** [comment]
I wonder why you changed min_value and max_value in SFOutputStream. This looks wrong. These values are not positions but actual sample values, and their range is signed integer 32 bit. If you change it here, you must also change it for input, but I don't think it is necessary at all.

**Comment by mnordstr** [comment]
You are right, and they were the reason the file could not be validated. I was testing and they were left there incorrectly apparently.

Now it can validate the files created as RF64:

```console
sndfile-info awtest2.wav
========================================
File : awtest2.wav
Length : 23315812
RF64
  WAVE
ds64 : 28
  Riff size : 23315804
  Data size : 23315708
  Frames    : 5828927
  Table length : 0
fmt  : 40
  Format        : 0xFFFE => WAVE_FORMAT_EXTENSIBLE
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 4
  Bit Width     : 16
  Bytes/sec     : 176400
  Valid Bits    : 16
  Channel Mask  : 0x3 (L, R)
  Subformat
    esf_field1 : 0x1
    esf_field2 : 0x0
    esf_field3 : 0x10
    esf_field4 : 0x80 0x0 0x0 0xAA 0x0 0x38 0x9B 0x71
    format : pcm
data : 0xFFFFFFFF
End

----------------------------------------
Sample Rate : 44100
Frames      : 5828927
Channels    : 2
Format      : 0x00220002
Sections    : 1
Seekable    : TRUE
Duration    : 00:02:12.175
Signal Max  : 32095 (-0.18 dB)

./audiowmark get awtest2.wav
pattern  0:00 f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0 1.412 0.290 CLIP-B
pattern  0:05 f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0 1.383 0.079 A
pattern  0:57 f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0 1.375 0.076 B
pattern  0:57 f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0 1.379 0.077 AB
pattern  1:20 f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0 1.395 0.135 CLIP-B
pattern   all f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0 1.379 0.077
```

Thanks for your assistance!
