### ISSUE TITLE
Short Files

### ISSUE THREAD

**Issue by Coice** [swesterfeld/audiowmark#20]
What is the minimum length supported by audiowmark? I have short audio files (sound effects) from 100ms to 5s in length, what are your thoughts on adding a watermark? Thanks for your time.

**Comment by swesterfeld** [comment]
There is no fixed minimum length, audiowmark embeds and decodes the watermark for files of (almost) any length. The probability of successfully detecting the watermark mainly depends on
 - the content of the file
 - the watermarking strength (higher strength -> shorter files)
 - long/short payload (short payload -> shorter files)
 - how much the file is altered after watermarking (i.e. mp3 compression/...?)

The default strength 10 (with long payload) works reliably if 50 seconds of audio are available. If you use short payload and a strength of 15 you may not get 100% detection probability, but maybe like 99% if 5 seconds of audio are available. I haven't done systematic experiments with very short files, but my intuition would be that 1 second can be done, but you'd have to use a pretty high strength, so the quality would not be great. I doubt that it would work with 100ms audio at all.

**Comment by Coice** [comment]
That was helpful, thank you!
