### ISSUE TITLE
--key does not work with videowmark

### ISSUE THREAD

**Issue by DashLt** [swesterfeld/audiowmark#23]
Hello!

Thank you for this excellent program. I've encountered an issue when trying to add a watermark with a key. 

The command & output:
```
videowmark add --key filename.key /source/path /dest/path message
Audio Codec:  -c:a aac -ab 193247
audiowmark: unsupported global option '--key' (use audiowmark -h)
videowmark: error: watermark generation failed (audiowmark)
```

Looking at the videowmark code, it seems that the key is being added to the global args:
`    --key ) AUDIOWMARK_ARGS+=("--key" "$2"); shift 2 ;;`

A possible solution would be to add a separate variable for after-command args. I will try to do this later and open a PR, though my bash is not very good...

**Comment by swesterfeld** [comment]
Thanks, should be fixed by eced66f.
