### ISSUE TITLE
videowamrk, audiowmark add cant, 6channel, 3h28m

### ISSUE THREAD

**Issue by jiamn** [swesterfeld/audiowmark#30]
I have bbb.mkv, 
mediainfo bbb.mkv 
Audio
ID                                       : 1
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 3 h 28 min
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 573 MiB (11%)
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

First, cant output video file use videowmark, 
change shell command line, ffmpeg $FFMPEG_VERBOSE -y -i "$in_file" -f wav -rf64 auto "$orig_wav"

get bbb.wav 7,211,114,634bytes

General
Complete name                            : bbb.wav
Format                                   : Wave
Format profile                           : RF64
File size                                : 6.72 GiB
Duration                                 : 3 h 28 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 4 608 kb/s
Writing application                      : Lavf58.76.100

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 00000001-0000-0010-8000-00AA00389B71
Duration                                 : 3 h 28 min
Bit rate mode                            : Constant
Bit rate                                 : 4 608 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Stream size                              : 6.72 GiB (100%)

Second, cant get orginal time-length wav and audiowmark return 0
    use audiowmark add bbb.wav bbb_git.wav --key temp.key 0123456

bbb_git.wav 7,211,114,540 bytes
General
Complete name                            : bbb_git.wav
Format                                   : Wave
File size                                : 6.72 GiB
Duration                                 : 3 h 28 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 4 608 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 3 h 28 minb
Bit rate mode                            : Constant
Bit rate                                 : 4 608 kb/s
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Stream size                              : 6.72 GiB (100%)

but ffprobe bbb_git.wav
Guessed Channel Layout for Input Stream #0.0 : 5.1
Input #0, wav, from 'bbb_git.wav':
  Duration: 01:24:22.76, bitrate: 11394 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 6 channels, s16, 4608 kb/s
play by MS mediaplayer , it is 01:24:23.

**Comment by swesterfeld** [comment]
This looks like it is related to

 - https://github.com/swesterfeld/audiowmark/issues/2

I'm not completely sure what we should change on audiowmark. I see a few options here:

 - always write RF64 output files (but this may break some use cases where you have a program that doesn't support RF64 after audiowmark)
 - automatically write RF64 output file if input is RF64 (same problem)
 - always write RF64 output files if a special option is used (like `--always-rf64`)
 - try to auto-detect size and use RF64 if size is large
 - automatically write RF64 output file if input is RF64 and a special option is used (like `--auto-rf64`)

The last version is probably the one that is least likely to cause problems.

**Comment by jiamn** [comment]
I can't get file by format raw.

audiowmark add bbb_wav.wav bbb_wav_add.wav f0 --format raw --raw-rate 48000 --raw-channels 6 --raw-bits 16 --key temp.key
Input:        bbb_wav.wav
Raw Input:    48000 Hz, 6 Channels, 16 Bit (signed little-endian)
Output:       bbb_wav_add.wav
Raw Output:   48000 Hz, 6 Channels, 16 Bit (signed little-endian)
Message:      f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0
Strength:     10

Time:         unknown
Sample Rate:  48000
Channels:     6
Data Blocks:  242

 ffprobe bbb_wav_add.wav
bbb_wav_add.wav: Invalid data found when processing input

file can't play by mediaplayer.

wrong with command line? or audiowmark can't support group (6 channel 48000 sample rate 16bits)? or other?

**Comment by swesterfeld** [comment]
Ok, I've added support for rf64 output for audiowmark in this branch:

 * https://github.com/swesterfeld/audiowmark/tree/rf64-support

Could you please check that this solves your problem?

**Comment by jiamn** [comment]
./audiowmark add /mnt/bbb.wav ./bbb_rf64.wav f0 --key /mnt/temp.key
Input:        /mnt/bbb.wav
Output:       ./bbb_rf64.wav
Message:      f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0
Strength:     10

Time:         208:39
Sample Rate:  48000
Channels:     6
Data Blocks:  242

BUT !!! 
ffprobe -hide_banner bbb_rf64.wav
Input #0, wav, from 'bbb_rf64.wav':
  Duration: 01:24:22.76, bitrate: 11394 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 6 channels, s16, 4608 kb/s

mediainfo bbb_rf64.wav
General
Complete name                            : bbb_rf64.wav
Format                                   : Wave
File size                                : 6.72 GiB
Duration                                 : 3 h 28 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 4 608 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 3 h 28 min
Bit rate mode                            : Constant
Bit rate                                 : 4 608 kb/s
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Stream size                              : 6.72 GiB (100%)

BUT!!! core dump
./audiowmark get ./bbb_rf64.wav  --key /mnt/temp.key
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

machine:
free
               total        used        free      shared  buff/cache   available
：   16018168      301164     5864952        1520     9852052    15385116
：    2097148        4352     2092796

**Comment by swesterfeld** [comment]
> ./audiowmark add /mnt/bbb.wav ./bbb_rf64.wav f0 --key /mnt/temp.key

Ok a little background here: I believe that your problem is caused by the fact that plain WAV files can not represent huge wave files (like yours). This is why in your case a plain WAV file is not enough. RF64 wav files don't have this restriction. However, I didn't want to make `audiowmark` always output RF64 wav files because of compatibility issues with programs that a user might want to use after the watermarking. So the branch adds a new command line option `--output-format rf64` which you need to use for your case. I make `videowmark` do that automatically for the temp files it creates.

So to test this:
- use `audiowmark` with the `--output-format rf64` option
- use `videowmark` which was your original use case, it should just work because it uses rf64 internally

> ./audiowmark get ./bbb_rf64.wav --key /mnt/temp.key
> terminate called after throwing an instance of 'std::bad_alloc'

There is no easy fix here. The watermark detection was implemented under the assumption that it is ok to load the file to memory first. In memory 32 bit is used per sample, so for an ordinary 16 bit wav file, you'd need approximately twice the size it has on disk, plus some extra memory that is needed for other stuff. I currently don't plan to implement a different solution here.

A simple workaround would be splitting the input file into smaller files before detection.

**Comment by jiamn** [comment]
%% use audiowmark with the --output-format rf64 option
It's ok with --output-format rf64. 
It's matter whether use this option if many files. so follow the last instruction

%% use videowmark which was your original use case, it should just work because it uses rf64 internally
I haven't test this. because this instruction \/ 
%% A simple workaround would be splitting the input file into smaller files before detection.
If job have many video files with less length or bigger, Good idea is split file.
