### ISSUE TITLE
fails to compile with clang15

### ISSUE THREAD

**Issue by ehaupt** [swesterfeld/audiowmark#36]
I've tried compiling with clang 15.0.7:

```
c++ --version
FreeBSD clang version 15.0.7 (https://github.com/llvm/llvm-project.git llvmorg-15.0.7-0-g8dfdcc7b7bf6)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
```

and got the following errors: [audiowmark-0.6.1.log](https://github.com/swesterfeld/audiowmark/files/11702861/audiowmark-0.6.1.log)

**Note**: There are no issues with clang 14.0.5:

```
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd13.2
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by swesterfeld** [comment]
Looks like the same problem as #29. If so, it has been fixed in git already.

**Comment by ehaupt** [comment]
> Looks like the same problem as https://github.com/swesterfeld/audiowmark/issues/29. If so, it has been fixed in git already.

Can confirm, that fixes the issue. Thank you @swesterfeld.
