### ISSUE TITLE
zita-resampler not found after compiling from source

### ISSUE THREAD

**Issue by InvisioDigital** [swesterfeld/audiowmark#39]
Hello, I am having trouble after compiling from source. Commands listed in readme are running fine:
`./configure`
`make`
`make install`

I am then trying `audiowmark gen-key test.key` and get the following error:
`error while loading shared libraries: libzita-resampler.so.1: cannot open shared object file: No such file or directory`

libzita-resampler was recognized while running `./configure` and the file libzita-resampler.so.1 is located in /usr/local/lib64 but I am not sure where to move it or how to make it accessible for audiowmark.

The server uses EC2 instance with AWS AMI 2 Linux which is based on RHEL 7 in case that's relevant.

I would appreciate any help in this matter.

**Comment by swesterfeld** [comment]
I've been able to reproduce that it doesn't work out-of-the-box if zita-resampler is installed in a non-standard location, should be fixed by setting the rpath: e8b530d
