### ISSUE TITLE
autogen failed

### ISSUE THREAD

**Issue by elvquant** [swesterfeld/audiowmark#4]
$ ./autogen.sh 
Running: autoreconf -i && ./configure 
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:79: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:79: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
configure.ac:79: error: possibly undefined macro: AM_PATH_LIBGCRYPT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /opt/local/bin/autoconf failed with exit status: 1

**Comment by mnordstr** [comment]
Hi,

Did you install the required dependencies? Sounds like you're missing libgcrypt.

On Debian/Ubuntu:

sudo apt-get update && sudo apt-get install -y build-essential libfftw3-dev libsndfile1-dev automake autoconf libtool autoconf-archive libgcrypt20-dev libzita-resampler-dev libmpg123-dev

**Comment by elvquant** [comment]
Of course. All prerequirements are installed on macOS 10.13.
I also configured, compiled and running an older (pre-autoconf version 0.5.0)

**Comment by swesterfeld** [comment]
The error message means that you don't have the macro `AM_PATH_LIBGCRYPT` available, therefore autogen.sh fails. On my Ubuntu 20.04, the m4 file needed is called `/usr/share/aclocal/libgcrypt.m4` and this is provided when installing the `libgcrypt20-dev` package.

So I see two solutions here: either you find a way to provide this m4 file or you build from tarball, then everything you need to build is automatically included in the configure script.

**Comment by tscole** [comment]
Hi - I'm also trying to use this on macOS and getting the same / similar errors. I overcame the first by running "brew install libgcrypt" but I am now getting subsequent errors for missing dependencies and these don't appear available via brew.

Pardon my ignorance - by I am a web developer by trade and don't know how / what is meant by "build from tarball".

**Comment by swesterfeld** [comment]
Ok, "build from tarball" is another way of saying "build a stable release", the release files are often tar archives. Stable releases are available from https://uplex.de/audiowmark/. Using the ./configure should complain if something is missing.

I'm sorry to say: you need all necessary dependencies before you can build audiowmark. If they are not available from brew you could try to build from source. Not sure how difficult it would be if you tried to contribute the missing stuff to brew if you succeed. I must admit that I develop and test this software on linux only. For other platforms (macOS/Windows) I can merge compile or documentation fixes into the git repo, and try to help on github like here, but its not really a supported platform.

**Comment by normen** [comment]
Even with all libraries available I still get compilation errors on MacOS, see the infos I added in #7

**Comment by swesterfeld** [comment]
Ok, I don't really see anything more that remains to be done in this issue, so I'll close it.
