### ISSUE TITLE
Build for Mac OSX High Sierra 

### ISSUE THREAD

**Issue by Pythagorstudio** [swesterfeld/audiowmark#50]
Hi,
 I'm having troubles installing audiowmark on  mac HS. The error is 
No package 'fftw3f' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FFTW_CFLAGS
and FFTW_LIBS to avoid the need to call pkg-config.

I installed FFTW from FFTW site,brew install FFTW gave me errors
any ideas?
Many thanks

**Comment by swesterfeld** [comment]
You may want to report the problems with brew back to them, so that they can fix it.

If you installed FFTW from source, you need to ensure that it can be found during `configure`. In order to do so, you need to include the path where you installed FFTW in PKG_CONFIG_PATH. For instance if you installed FFTW in /usr/local, you would need something like:
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
```
before calling `configure`.

**Comment by Pythagorstudio** [comment]
Not working
here is more info
echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/pkgconfig:

ls /usr/local/lib/pkgconfig/ff*
/usr/local/lib/pkgconfig/fftw3.pc

No package 'fftw3f' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FFTW_CFLAGS
and FFTW_LIBS to avoid the need to call pkg-config.

**Comment by Pythagorstudio** [comment]
RTFM!! Thank you!
Now i have this after 'make'

Making all in src
  CXX      sfinputstream.o
sfinputstream.cc:188:47: error: use of undeclared identifier 'errno'
          while (count > 0 || (count == -1 && errno == EINTR));
                                              ^
sfinputstream.cc:188:56: error: use of undeclared identifier 'EINTR'
          while (count > 0 || (count == -1 && errno == EINTR));

**Comment by Pythagorstudio** [comment]
It works! Thank you !
