### ISSUE TITLE
Keys do not appear to work

### ISSUE THREAD

**Issue by tscole** [swesterfeld/audiowmark#6]
```
audiowmark --key test.key add test.wav output.wav 1234567890
audiowmark: error parsing commandline args (use audiowmark -h)
```

**Comment by normen** [comment]
I think the `add` has to go first, before the `--key`

**Comment by swesterfeld** [comment]
Yes, options for commands (like `add`) need to be specified after the command. Only global options which apply to all commands (like `--quiet`) can be used everywhere. I tried to make the error message a bit more informative. It says now:
```
audiowmark: unsupported global option '--key' (use audiowmark -h)
```
