### ISSUE TITLE
How to get format raw?

### ISSUE THREAD

**Issue by muyiwq** [swesterfeld/audiowmark#71]
hi,The original raw file is successfully embedded with watermark, but the format cannot be specified. What should I do?
 If it is an original audio stream data, how should I process it?
.----------------------------------------------------------------------------------------------------
/audiowmark add --format raw --raw-rate 8000 --raw-channels 2 --raw-input-bits 16 nomal.pcm nomal_embed.pcm 22335556223355562233555622335556        

Input:        nomal.pcm
Raw Input:    8000 Hz, 2 Channels, 16 Bit (signed little-endian)
Output:       nomal_embed.pcm
Raw Output:   8000 Hz, 2 Channels, 16 Bit (signed little-endian)
Message:      22335556223355562233555622335556
Strength:     10

Time:         unknown
Sample Rate:  8000
Channels:     2
Data Blocks:  0         

----------------------------------------------------------------------------------------------------------
./audiowmark get nomal_embed.pcm    
audiowmark: error loading nomal_embed.pcm: File contains data in an unknown format.
./audiowmark get --format raw  --raw-rate 8000 --raw-channels 2 --raw-input-bits 16 nomal_embed.pcm 
audiowmark: unsupported option '--format' for command 'get' (use audiowmark -h)

**Comment by muyiwq** [comment]
I found a way to test the linear PCM data and convert the output PCM to WAV format, which can be extracted normally.
 Why is the raw data in alaw format embedded successfully, but the input PCM is also converted to WAV, but no information can be extracted?

**Comment by muyiwq** [comment]
I found a way to test the linear PCM data and convert the output PCM to WAV format, which can be extracted normally.
 Why is the raw data in alaw format embedded successfully, but the alaw_embeded output PCM is also converted to WAV, but no information can be extracted?

**Comment by muyiwq** [comment]
I tried to convert the linear (8k16bit1ch) watermarked audio pcm data to wav format to extract the watermark, but after converting to alaw format, then to linear, and then to wav format, the watermark could not be extracted. Is this watermark gone after lineToalaw and alawToLine? ?

**Comment by tim-janik** [comment]
> hi,The original raw file is successfully embedded with watermark, but the format cannot be specified. What should I do? If it is an original audio stream data, how should I process it? .---------------------------------------------------------------------------------------------------- /audiowmark add --format raw --raw-rate 8000 --raw-channels 2 --raw-input-bits 16 nomal.pcm nomal_embed.pcm 22335556223355562233555622335556
> 
> Input: nomal.pcm Raw Input: 8000 Hz, 2 Channels, 16 Bit (signed little-endian) Output: nomal_embed.pcm Raw Output: 8000 Hz, 2 Channels, 16 Bit (signed little-endian) Message: 22335556223355562233555622335556 Strength: 10
> 
> Time: unknown Sample Rate: 8000 Channels: 2 Data Blocks: 0
> 
> ./audiowmark get nomal_embed.pcm audiowmark: error loading nomal_embed.pcm: File contains data in an unknown format. ./audiowmark get --format raw --raw-rate 8000 --raw-channels 2 --raw-input-bits 16 nomal_embed.pcm audiowmark: unsupported option '--format' for command 'get' (use audiowmark -h)

You probably wantg to use --input-format raw in the last case. See here for more info:
https://github.com/swesterfeld/audiowmark#raw-streams
