### ISSUE TITLE
Increased file size

### ISSUE THREAD

**Issue by saicharanpogul** [swesterfeld/audiowmark#8]
Why is the output of audio file size is increased when its watermarked? Although the message added is just 128bit and its added multiple times which doesn't even increase by 100 bytes. But i see the increase in size of audio files by 10s of MB. Not sure am I missing out something. Any help with this is appreciated.

**Comment by badboy-tian** [comment]
any update ?

**Comment by swesterfeld** [comment]
What you're likely to see here is that you used a compressed file format as input (such as mp3 or ogg or flac) and audiowmark wrote an uncompressed wav file as output (which is of course larger than the input file). This is normal. If you want a compressed file you need to re-encode after watermarking.

Also see this discussion: https://groups.google.com/g/audiowmark/c/gmzPAzLE1Uo

**Comment by badboy-tian** [comment]
> What you're likely to see here is that you used a compressed file format as input (such as mp3 or ogg or flac) and audiowmark wrote an uncompressed wav file as output (which is of course larger than the input file). This is normal. If you want a compressed file you need to re-encode after watermarking.
> 
> Also see this discussion: https://groups.google.com/g/audiowmark/c/gmzPAzLE1Uo

Thanks
